/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_memoirs_travel_travelmemoirs_MainActivity.h"
/* Header for class com_memoirs_travel_travelmemoirs_MainActivity */

JNIEXPORT jstring JNICALL Java_com_memoirs_travel_travelmemoirs_MainActivity_getStringFromNative
  (JNIEnv * env, jobject obj){
    return (*env)->NewStringUTF(env,"Di si miskooo");
}

